### ISSUE TITLE
[TO DO] Myself to create PR in __init__ + suggestions for classes

### ISSUE THREAD

**Issue by alicecommits** [TheCodeForge/pyrena#1]
Good afternoon,
I've had a couple gating activities that made diving into this repo delayed by a couple weeks.

- Just to let you know I've started going through the repo and I have a couple Qs + enhancement 'tweaks' to offer, so I will create PRs during the upcoming weeks for these.
- I'll also start digging in the different subclasses of the 'classes' folder. I'm going to start with the **change** subclass, that I'll also explore as an end-user in the upcoming days, as I need to perform a job around it for my team and myself.

_Note: sorry again for opening an issue. Given that it's been a while since you opened the repo per my request, I just wanted to make you aware I'm cracking on!
If more convenient in the future, maybe I can reach out via a generic email?_

Thanks,

**Comment by TheCodeForge** [comment]
Issues is fine. Take your time; there's no pressure.

**Comment by alicecommits** [comment]
Hi again CodeForge,
I've had some feedback from Arena that they would appreciate merging the repo into a Git organization they're working on and will be available pretty soon.
What do you think about it? Would you be ok to be a contributor? Are you an employee of a company that uses Arena PLM and QMS?
I'm in that situation, therefore I'd be comfortable contributing via their upcoming community.

Could we please reach you out via some email / contact info?

Please let me know what you think.
Have a nice day,

**Comment by TheCodeForge** [comment]
If Arena/PTC wants to make this an officially sanctioned package, that's a discussion I'd be willing to have with them directly.

**Comment by TheCodeForge** [comment]
@PTCinc or someone affiliated is welcome to reach out
