### ISSUE TITLE
[Question] Merging or Forking that repo for newly launched PTC-Arena GitHub orga

### ISSUE THREAD

**Issue by alicecommits** [TheCodeForge/pyrena#2]
Hi CodeForge,
As explained in the title Arena just launched their own public organization: https://github.com/orgs/ptc-arena/repositories

A while ago they told me they would welcome contributions to it, once born.
Now it is, are you interested in migrating your repo there or forking it? FYI I still intend to use portions of your classes, as they're very conveniently written for Arena custom app tools development, that I'm co-leading at my current company.

Thanks,

**Comment by TheCodeForge** [comment]
Very cool. Will check into it.

**Comment by TheCodeForge** [comment]
https://github.com/orgs/ptc-arena/discussions/4
